### PR TITLE
added text to Canadian-North

### PR DESCRIPTION
**Pull request by AdityaBansal1402**

### CODE REVIEW

**Comment by xxXWarMachineRoXxx** [comment]
@AdityaBansal1402  please add the screenshot too

**Comment by AdityaBansal1402** [comment]
Canadian-North ss1
Canadian-North ss2

**Comment by AdityaBansal1402** [comment]
Canadian-North ss3

**Comment by xxXWarMachineRoXxx** [comment]
@AdityaBansal1402  Please fix the image too , Look into Issue #3 for hotfix and vote for the hotfix that suits you.


after that , please update the image accordingly

**Review by xxXWarMachineRoXxx — CHANGES_REQUESTED** [review]
Content is fine , image is missing

**Review by xxXWarMachineRoXxx — APPROVED** [review]
I'm merging it for now, Might try and make changes

**Pull request merged**
